### ISSUE TITLE
Incorrect transforms?

### ISSUE THREAD

**Issue by Roy-Orbison** [leesherwood/Orientation-Fix-PHP#3]
Are `3` and `4` back to front?

Also, "Upside-Down & Flipped along horizontal axis" is just rotated 180°.

**Comment by Roy-Orbison** [comment]
Reference: https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

**Comment by leesherwood** [comment]
You could be right. It was never heavily tested when I wrote it to answer a StackOverflow question and I can't say i've used ever used it myself.

Merged your pull request, so hopefully that helps people out. Thanks :)

**Comment by Roy-Orbison** [comment]
I'm not using the code as is; it had high search rank, so figured it'd be a
good reference for others.
